name: Deploy VitePress to GitHub Pages

on:
  # 当推送到 main 分支时触发工作流
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # 获取所有历史记录和标签
          fetch-depth: 0

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'  # 添加 npm 缓存

      # 安装依赖
      - name: Install dependencies
        run: npm ci

      # 构建 VitePress 项目
      - name: Build VitePress site
        run: npm run docs:build
        env:
          NODE_ENV: production  # 确保在生产环境下构建

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          force_orphan: true    # 添加这行以清理历史部署

